###

GET http://localhost:3000/api/product

###
POST http://localhost:3000/api/product
Content-Type: application/json

{
    "nombre": "cajaMisteriosa",
    "precio": 200000
}

###

GET http://localhost:3000/api/product/4

###

POST http://localhost:3000/api/product HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "cajaMisteriosa2: Ahora es personal", 
    "edad": 3 
}

###

PUT http://localhost:3000/api/product/4 HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "CajaMisteriosa3: La vengaza", 
    "edad": 4
}

###
DELETE http://localhost:3000/api/users/4